### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by gp201**
## Checklist
- [x] I have successfully deployed my own instance of Oppiabot.
  - You can find instructions for doing this [here](https://github.com/oppia/oppiabot/wiki/Deploying-your-own-instance-of-the-oppiabot).
- [x] I have manually tested all the changes made in this PR following the [manual tests matrix](https://github.com/oppia/oppiabot/wiki/Manual-Tests-Matrix).

### CODE REVIEW

**Comment by gp201** [comment]
Hi! gp201Welcome to Oppia! Please could you follow the instructions https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia#setting-things-up to get started? You'll need to do this before we can accept your PR. Thanks!

**Comment by gp201** [comment]
Hi! gp201Welcome to Oppia! Please could you follow the instructions https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia#setting-things-up to get started? You'll need to do this before we can accept your PR. Thanks!

**Comment by gp201** [comment]
Hi! gp201Welcome to Oppia! Please could you follow the instructions https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia#setting-things-up to get started? You'll need to do this before we can accept your PR. Thanks!

**Comment by gp201** [comment]
Hi! gp201Welcome to Oppia! Please could you follow the instructions https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia#setting-things-up to get started? You'll need to do this before we can accept your PR. Thanks!

**Comment by gp201** [comment]
Hi! @gp201 Welcome to Oppia! Please could you follow the instructions https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia#setting-things-up to get started? You'll need to do this before we can accept your PR. Thanks!

**Comment by gp201** [comment]
Hi! @gp201 Welcome to Oppia! Please could you follow the instructions https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia#setting-things-up to get started? You'll need to do this before we can accept your PR. Thanks!

**Comment by gp201** [comment]
Hi! @gp201 Welcome to Oppia! Please could you follow the instructions https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia#setting-things-up to get started? You'll need to do this before we can accept your PR. Thanks!

**Comment by gp201** [comment]
Hi! @gp201 Welcome to Oppia! Please could you follow the instructions https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia#setting-things-up to get started? You'll need to do this before we can accept your PR. Thanks!

**Comment by gp201** [comment]
Hi! @gp201 Welcome to Oppia! Please could you follow the instructions https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia#setting-things-up to get started? You'll need to do this before we can accept your PR. Thanks!

**Comment by gp201** [comment]
Hi! @gp201 Welcome to Oppia! Please could you follow the instructions https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia#setting-things-up to get started? You'll need to do this before we can accept your PR. Thanks!

**Comment by gp201** [comment]
Hi! @gp201 Welcome to Oppia! Please could you follow the instructions https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia#setting-things-up to get started? You'll need to do this before we can accept your PR. Thanks!

**Comment by gp201** [comment]
Hi! @gp201 Welcome to Oppia! Please could you follow the instructions https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia#setting-things-up to get started? You'll need to do this before we can accept your PR. Thanks!

**Comment by gp201** [comment]
Hi! @gp201 Welcome to Oppia! Please could you follow the instructions https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia#setting-things-up to get started? You'll need to do this before we can accept your PR. Thanks!

**Comment by gp201** [comment]
Hi! @gp201 Welcome to Oppia! Please could you follow the instructions https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia#setting-things-up to get started? You'll need to do this before we can accept your PR. Thanks!

**Comment by gp201** [comment]
Hi! @gp201 Welcome to Oppia! Please could you follow the instructions https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia#setting-things-up to get started? You'll need to do this before we can accept your PR. Thanks!

**Comment by gp201** [comment]
Hi! @gp201 Welcome to Oppia! Please could you follow the instructions https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia#setting-things-up to get started? You'll need to do this before we can accept your PR. Thanks!

**Comment by gp201** [comment]
Hi! @gp201 Welcome to Oppia! Please could you follow the instructions https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia#setting-things-up to get started? You'll need to do this before we can accept your PR. Thanks!

**Comment by gp201** [comment]
Hi! @gp201 Welcome to Oppia! Please could you follow the instructions https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia#setting-things-up to get started? You'll need to do this before we can accept your PR. Thanks!

**Comment by gp201** [comment]
Hi! @gp201 Welcome to Oppia! Please could you follow the instructions https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia#setting-things-up to get started? You'll need to do this before we can accept your PR. Thanks!

**Comment by gp201** [comment]
Hi! @gp201 Welcome to Oppia! Please could you follow the instructions <a href=https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia#setting-things-up>here</a> to get started? You'll need to do this before we can accept your PR. Thanks!

**Comment by gp201** [comment]
Hi! @gp201 Welcome to Oppia! Please could you follow the instructions <a href=https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia#setting-things-up>here</a> to get started? You'll need to do this before we can accept your PR. Thanks!

**Comment by gp201** [comment]
Hi! @gp201 Welcome to Oppia! Please could you follow the instructions <a href=https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia#setting-things-up>here</a> to get started? You'll need to do this before we can accept your PR. Thanks!

**Comment by niket2219** [comment]
Hi Oppia developer could you assign me this issue to be fixed?

**Pull request closed without merging**
